### PR TITLE
Fixed empty folder not showing in file share once uploaded

### LINKED ISSUE #1001: The empty folder doesn't show in the file share after uploading it
**OS:** Win 10
**Build:** 20210905.1
**Regression:** Not a regression

**Repro Steps:**
1. Right click one file share --> Click "Upload Folder..." --> Select one **empty folder** to upload.
2. Check whether the empty folder shows in this file share.

**Expect:**
The empty folder shows well in this file share.

**Actual:**
The empty folder doesn't show in this file share, but the output log shows "Successfully uploaded...".
image

**More Info:**
1. This issue does not reproduce in Storage Explorer.
2. Upload the empty folder to this file share from Storage Explorer then refresh the file share node in VS Code, the empty folder shows well in VS Code.
3. This issue also reproduces on the previous released storage extension 0.12.1.

### PR DESCRIPTION
**Pull request by motm32**
Fixes #1001

### CODE REVIEW

File: src/utils/uploadUtils.ts [hunk 1]
```diff
@@ -40,7 +40,18 @@ export async function uploadLocalFolder(
...
+        useWildCard = false;
+        var path = require('path');
+        destPath = path.dirname(destPath);
+        if(destPath == '.')
+        {
+            destPath = '';
+        }
+    }
+    const src: ILocalLocation =
+    createAzCopyLocalLocation(sourcePath, useWildCard);
```
Comment (bwateratmsft) [inline src/utils/uploadUtils.ts:54]: Do you have ESLint installed? There's a couple of spacing irregularities in this file that usually ESLint fixes automatically.

Comment (motm32) [reply src/utils/uploadUtils.ts:54]: Hmm I don't think I have it installed but I'll check and install it if I don't have it.

File: src/utils/directoryUtils.ts [hunk 2]
```diff
@@ -88,3 +89,11 @@ export async function doesDirectoryExist(parent: FileShareTreeItem | DirectoryTr
 export function isTreeItemDirectory(node: AzExtTreeItem): boolean {
     return /directory/i.test(node.contextValue);
 }
+
+export function doesDirectoryContainFiles(srcPath: string) : boolean {
+    const files = readdirSync(srcPath);
```
Comment (alexweininger) [inline src/utils/directoryUtils.ts:94]: [Using the node `fs` API won't work in all VS Code environments (namely virtual workspaces).](https://github.com/microsoft/vscode/wiki/Virtual-Workspaces#review-that-the-code-is-ready-for-virtual-resources) Instead, VS Code provides the `workspace.fs` API. Use `workspace.fs.readDirectory` here instead.

File: src/utils/directoryUtils.ts [hunk 3]
```diff
@@ -90,9 +89,9 @@ export function isTreeItemDirectory(node: AzExtTreeItem): boolean {
     return /directory/i.test(node.contextValue);
 }
 
-export function doesDirectoryContainFiles(srcPath: string) : boolean {
-    const files = readdirSync(srcPath);
-    if (files.length > 0) {
+export async function doesDirectoryContainFiles(uri: Uri) : Promise<boolean> {
+    const files = workspace.fs.readDirectory(uri);
+    if ((await files).length > 0) {
```
Comment (alexweininger) [inline src/utils/directoryUtils.ts:94]:
```suggestion
    const files = await workspace.fs.readDirectory(uri);
    if (files.length > 0) {
```

File: src/utils/directoryUtils.ts [hunk 4]
```diff
@@ -88,3 +88,11 @@ export async function doesDirectoryExist(parent: FileShareTreeItem | DirectoryTr
 export function isTreeItemDirectory(node: AzExtTreeItem): boolean {
     return /directory/i.test(node.contextValue);
 }
+
+export async function doesDirectoryContainFiles(uri: Uri) : Promise<boolean> {
```
Comment (alexweininger) [inline src/utils/directoryUtils.ts:92]: I think this function fits best in `utils/fs.ts` alongside other local filesystem utils. The functions in `directoryUtils.ts` are related to Azure Storage File Share directories rather than local filesystem directories.

File: src/utils/uploadUtils.ts [hunk 5]
```diff
@@ -40,7 +40,18 @@ export async function uploadLocalFolder(
     messagePrefix?: string,
 ): Promise<void> {
     const fromTo: FromToOption = destTreeItem instanceof BlobContainerTreeItem ? 'LocalBlob' : 'LocalFile';
-    const src: ILocalLocation = createAzCopyLocalLocation(sourcePath, true);
+    const uri = vscode.Uri.file(sourcePath);
+    let useWildCard: boolean = true;
+    if(!(await doesDirectoryContainFiles(uri))){
```
Comment (alexweininger) [inline src/utils/uploadUtils.ts:45]: Since we're checking if the directory is empty here, we can be more direct and rename/refactor `doesDirectoryContainFiles` into `isDirectoryEmpty` or `isEmptyDirectory`. That way we don't have to negate the result inside the condition.

File: src/utils/fs.ts [hunk 6]
```diff
@@ -14,3 +15,11 @@ export function isSubpath(expectedParent: string, expectedChild: string): boolea
     const relativePath: string = path.relative(expectedParent, expectedChild);
     return relativePath !== '' && !relativePath.startsWith('..') && relativePath !== expectedChild;
 }
+
+export async function isEmptyDirectory (uri: Uri) : Promise<boolean> {
```
Comment (alexweininger) [inline src/utils/fs.ts:19]: nit: Remove the extra spaces on this line

**Review by alexweininger — DISMISSED** [review]

File: src/utils/uploadUtils.ts (hunk 1 above)
Comment (alexweininger) [reply src/utils/uploadUtils.ts:55]: Could you try formatting this file with the "Format Document" command? There are some formatting things that VS Code + ES Lint should be able to take care of.

**Review by alexweininger — APPROVED** [review]
