### PR TITLE
Browse static website...

### LINKED ISSUE #152: "Browse to website" for web hosting enabled accounts
Two parts to this with the same functionality 

1. Add a context menu item to an account/container to browse to the site (also needs "copy site URL")
1. Prompt user to browse to site upon completed deployment

Related to #146

### LINKED ISSUE #174: Deploying to Static Website doesn't display the notification after disabling static website in portal
Repro Steps:
1. Create one GPV2 account in portal.
2. Back to VS Code and set the "azureStorage.preview.staticWebsites" as true in User Settings.
3. Right click the created v2 account -> Select 'Deploy to Static Website...' -> Check the notification 'Website hosting is not enabled...' displays in bottom-right. -> Click 'Yes' then enable the static website in portal.
4. Deploy the account.
5. Right click the same account -> Click 'Configure Static Website' -> Disable the static website in portal.
6. Repeat Step4 and check whether the notification pops up or not.

Expect:
The notification 'Website hosting is not enabled...' displays in bottom-right.
notification

Actual:
No notification displays and it can be deployed successfully.

### LINKED ISSUE #175: Detect if the storage account supports website hosting and give error message if not
Repro Steps:
1. Right click one V1 storage account and select 'Deploy to Static Website...'.
2. Check the prompting message.

Expect:
Display a clear prompting message to say 'This storage account is not a V2 storage account. Or please select a GPV2 storage account'.

Actual:
Prompt the customer to enable the 'Website hosting', then display a blank website after clicking 'Yes'.
actual

### PR DESCRIPTION
**Pull request by StephenWeatherford**
Use new SDK functionality to:
- Add "Browse Static Website…", fixes #152
- Allow browsing after deploy (rather than asking them to go to portal)
- Ensure storage account can support hosted websites when deploying, browsing etc. (e.g. must be a V2 storage account), fixes #174, fixes #175
- Ensure storage account has hosted websites enabled when deploying, etc., and if not, ask if they want to configure
- Ensure website hosting has an index document set when browsing, and if not, ask if they want to - configure (fixes portal stupidity)

### CODE REVIEW

File: src/azureStorageExplorer/blobContainers/blobContainerNode.ts [hunk 1]
```diff
@@ -322,15 +327,39 @@ export class BlobContainerNode implements IAzureParentTreeItem, ICopyUrl {
             // Upload files as blobs
             await this.uploadFiles(sourceFolderPath, filePathsWithAzureSeparator, destBlobFolder, properties, updateProgress, cancellationToken);
 
-            ext.outputChannel.appendLine("Deployment to static website complete.");
+            let webEndpoint = this.getPrimaryWebEndpoint();
+            if (!webEndpoint) {
+                throw new Error(`Could not obtain the primary web endpoint for ${this.storageAccount.name}`);
+            }
+
+            ext.outputChannel.appendLine(`Deployment to static website complete. CTRL+Click to browse: ${webEndpoint}`);
```
Comment (PrashanthCorp) [inline src/azureStorageExplorer/blobContainers/blobContainerNode.ts]: Seems OS specific. IIRC, Mac would be Cmd.

File: src/azureStorageExplorer/blobContainers/blobContainerNode.ts [hunk 2]
```diff
@@ -322,15 +327,39 @@ export class BlobContainerNode implements IAzureParentTreeItem, ICopyUrl {
...
             if (parseError(error).isUserCancelledError) {
                 ext.outputChannel.appendLine("Deployment canceled.");
-                throw error;
             }
+            throw error;
         }
     }
 
+    public getPrimaryWebEndpoint(): string | undefined {
+        // Right now we only support only web endpoint per storage account
```
Comment (PrashanthCorp) [inline src/azureStorageExplorer/blobContainers/blobContainerNode.ts]: only support one?

File: src/azureStorageExplorer/blobContainers/blobContainerNode.ts [hunk 3]
```diff
@@ -322,15 +327,39 @@ export class BlobContainerNode implements IAzureParentTreeItem, ICopyUrl {
...
+        if (!(node.treeItem instanceof BlobContainerNode)) {
+            throw new Error(`Unexpected node type: ${node.treeItem.contextValue}`);
+        }
+
+        let storageAccountNode = node.parent && node.parent.parent;
+        if (storageAccountNode && storageAccountNode.treeItem instanceof StorageAccountNode) {
+            return <IAzureParentNode<StorageAccountNode>>storageAccountNode;
+        } else {
+            throw new Error("Couldn't find storage account node for container");
+        }
```
Comment (PrashanthCorp) [inline src/azureStorageExplorer/blobContainers/blobContainerNode.ts]: Can you fill me in on the error case? It looks like using `ext.ui.quickpick` with the appropriate contextValue would obviate this.

File: src/azureStorageExplorer/selectStorageAccountNodeForCommand.ts [hunk 4]
```diff
@@ -0,0 +1,66 @@
...
+import { ext } from "../extensionVariables";
+import { BlobContainerNode } from "./blobContainers/blobContainerNode";
+import { StorageAccountNode } from "./storageAccounts/storageAccountNode";
+
+/**
+ * Given a node argument for a command, if it is:
+ *   1) undefined, then query the user for a storage account
+ *   2) a storage account node, then return it
+ *   3) a blob container node, then return the storage account node
+ *   4) anything else, then throw an internal error
```
Comment (PrashanthCorp) [inline src/azureStorageExplorer/selectStorageAccountNodeForCommand.ts]: Would naming the function `selectStorageAccountNodeFromBlob` make 4 more explicit? 
It looks like this file is targeted towards static file hosting, but it's not very obvious from the name. 

Feel free to ignore this comment. :)

File: src/azureStorageExplorer/blobContainers/blobContainerNode.ts [hunk 5]
```diff
@@ -322,15 +327,39 @@ export class BlobContainerNode implements IAzureParentTreeItem, ICopyUrl {
...
+    }
```
Comment (PrashanthCorp) [inline src/azureStorageExplorer/blobContainers/blobContainerNode.ts]: I'm a little puzzled regarding the placement of this function. 
I don't see a reference to class members (`this.` etc.)
I only see one use of it - `selectStorageAccountNodeForCommand`. 

What am I missing regarding placing it here (as opposed to `selectStorageAccountNodeForCommand.ts`) ?

File: src/azureStorageExplorer/storageAccounts/storageAccountNode.ts [hunk 6]
```diff
@@ -125,12 +135,123 @@ export class StorageAccountNode implements IAzureParentTreeItem {
...
+        // Refresh the storage account first to make sure $web has been picked up if new
+        await node.refresh();
+
         let groupTreeItem = <IAzureTreeItem>await this.getBlobContainerGroupNode();
 
         // Currently only the child with the name "$web" is supported for hosting websites
         let id = `${this.id}/${groupTreeItem.id || groupTreeItem.label}/${ext.staticWebsiteContainerName}`;
         let containerNode = <IAzureParentNode<BlobContainerNode>>await node.treeDataProvider.findNode(id);
-        return containerNode ? [containerNode] : [];
+        return containerNode;
```
Comment (PrashanthCorp) [inline src/azureStorageExplorer/storageAccounts/storageAccountNode.ts]: I don't see how this is now guaranteed to exist.

File: src/azureStorageExplorer/storageAccounts/storageAccountNode.ts [hunk 7]
```diff
@@ -125,12 +135,123 @@ export class StorageAccountNode implements IAzureParentTreeItem {
...
+    }
+
+    // This is the URL to use for browsing the website
+    public getPrimaryWebEndpoint(): string | undefined {
+        // Right now we only support only web endpoint per storage account
```
Comment (PrashanthCorp) [inline src/azureStorageExplorer/storageAccounts/storageAccountNode.ts]: only support one*

File: src/azureStorageExplorer/storageAccounts/storageAccountNode.ts [hunk 8]
```diff
@@ -125,12 +135,123 @@ export class StorageAccountNode implements IAzureParentTreeItem {
...
+            throw new UserCancelledError(msg);
+        }
+
+        if (!hostingStatus.indexDocument) {
+            let msg = "No index document has been set for this website.";
+            let result = await window.showErrorMessage(msg, configure);
+            if (result === configure) {
+                await commands.executeCommand('azureStorage.configureStaticWebsite', node);
+            }
+            throw new UserCancelledError(msg);
```
Comment (PrashanthCorp) [inline src/azureStorageExplorer/storageAccounts/storageAccountNode.ts]: Why is this failure case a `UserCancelledError`?

File: src/azureStorageExplorer/storageAccounts/storageAccountNode.ts [hunk 9]
```diff
@@ -125,12 +135,123 @@ export class StorageAccountNode implements IAzureParentTreeItem {
...
+            try {
+                accountType = await this.getAccountType();
+            } catch (error) {
+                // Ignore errors
+            }
+            if (accountType !== 'StorageV2') {
+                throw new Error("Only general purpose V2 storage accounts support static website hosting.");
+            }
+
+            throw new Error("This storage account does not support static website hosting.");
```
Comment (PrashanthCorp) [inline src/azureStorageExplorer/storageAccounts/storageAccountNode.ts]: Is there a more specific reason? I can imagine a user seeing the first error message about V2 accounts, creating a V2 account, then encountering this error.

File: src/azureStorageExplorer/blobContainers/blobContainerNode.ts [hunk 10]
```diff
@@ -322,15 +327,39 @@ export class BlobContainerNode implements IAzureParentTreeItem, ICopyUrl {
             // Upload files as blobs
             await this.uploadFiles(sourceFolderPath, filePathsWithAzureSeparator, destBlobFolder, properties, updateProgress, cancellationToken);
 
-            ext.outputChannel.appendLine("Deployment to static website complete.");
+            let webEndpoint = this.getPrimaryWebEndpoint();
+            if (!webEndpoint) {
+                throw new Error(`Could not obtain the primary web endpoint for ${this.storageAccount.name}`);
+            }
```
[the remark this answers is not in the document]
Comment (StephenWeatherford) [reply src/azureStorageExplorer/blobContainers/blobContainerNode.ts]: It appears to actually be a correct indication, but I've asked on e-mail.

File: src/azureStorageExplorer/blobContainers/blobContainerNode.ts (hunk 1 above)
Comment (StephenWeatherford) [reply src/azureStorageExplorer/blobContainers/blobContainerNode.ts]: Good point, changed to:
 ext.outputChannel.appendLine(`Deployment to static website complete. Primary web endpoint is ${webEndpoint}`);

File: src/azureStorageExplorer/blobContainers/blobContainerNode.ts (hunk 2 above)
Comment (StephenWeatherford) [reply src/azureStorageExplorer/blobContainers/blobContainerNode.ts]: Changed to:

// Right now only one web endpoint is supported per storage account

File: src/azureStorageExplorer/blobContainers/blobContainerNode.ts (hunk 3 above)
Comment (StephenWeatherford) [reply src/azureStorageExplorer/blobContainers/blobContainerNode.ts]: That's an internal error.  Shouldn't happen.

File: src/azureStorageExplorer/selectStorageAccountNodeForCommand.ts (hunk 4 above)
Comment (StephenWeatherford) [reply src/azureStorageExplorer/selectStorageAccountNodeForCommand.ts]: Anything related to static websites requires opt-in via the arguments.

File: src/azureStorageExplorer/blobContainers/blobContainerNode.ts (hunk 5 above)
Comment (StephenWeatherford) [reply src/azureStorageExplorer/blobContainers/blobContainerNode.ts]: Gets the storage account node that is the parent of "this" which is the blob container node.

I don't like the node/treeitem split, it causes stuff like this - many of the IAzureTreeItem have to have the related node passed in because there's no backpointer from tree item to node.  Thus functions like this that don't even use the this.  This is systemic to all our extensions.

And there's also this: #91, which makes it even more confusing.

Nothing I can do right now.

File: src/azureStorageExplorer/storageAccounts/storageAccountNode.ts (hunk 6 above)
Comment (StephenWeatherford) [reply src/azureStorageExplorer/storageAccounts/storageAccountNode.ts]: You mean "not"?  It should always be there, but I can't guarantee it.

Changed return value to include undefined.

File: src/azureStorageExplorer/storageAccounts/storageAccountNode.ts (hunk 7 above)
Comment (StephenWeatherford) [reply src/azureStorageExplorer/storageAccounts/storageAccountNode.ts]: // Right now Azure only supports one web endpoint per storage account

File: src/azureStorageExplorer/storageAccounts/storageAccountNode.ts (hunk 8 above)
Comment (StephenWeatherford) [reply src/azureStorageExplorer/storageAccounts/storageAccountNode.ts]: Because they chose not to configure it.

File: src/azureStorageExplorer/storageAccounts/storageAccountNode.ts (hunk 9 above)
Comment (StephenWeatherford) [reply src/azureStorageExplorer/storageAccounts/storageAccountNode.ts]: I'm not aware of any other reasons, this is a catch-all.
