### PR TITLE
Remove calls to vscode.workspace.rootPath

### LINKED ISSUE #453: Avoid using workspace.rootPath
This extension appears to be using the `workspace.rootPath` API. This is a deprecated property and may not work as expected. Please use `workspaceFolders` instead. More info:  https://github.com/microsoft/vscode/wiki/Adopting-Multi-Root-Workspace-APIs#eliminating-rootpath

https://github.com/microsoft/vscode/issues/69335

### PR DESCRIPTION
**Pull request by wwlorey**
Fixes #453

### CODE REVIEW

File: src/utils/workspaceUtils.ts [hunk 1]
```diff
@@ -0,0 +1,6 @@
+import * as vscode from 'vscode';
```
Comment (nturinski) [inline src/utils/workspaceUtils.ts]: Needs the Microsoft license at the top
