### PR TITLE
Fixes for CTI bugs

### LINKED ISSUE #305: Keep consistent between creating and deleting storage accounts
**OS**: All
**Build Version:** [20190214.4](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3207)
**Regression:**  Not a Regression

**Repro Steps:**
1. Right click the applied subscription and check the context menu of creating storage accounts.
2. Right click one storage account and check the context menu of deleting storage accounts.

**Expect:**
Keep consistent.

**Actual:**
Keep inconsistent.
image

### PR DESCRIPTION
**Pull request by PrashanthCorp**
Fixes #305, #303 

- selectStorageAccountTreeItemForCommand: Actually _return_ the treeItem once we configure the account for static websites. 
- Rename "Delete Account..." to "Delete Storage Account..." to maintain consistency with "Create Storage Account"

### CODE REVIEW

File: src/azureStorageExplorer/selectStorageAccountNodeForCommand.ts [hunk 1]
```diff
@@ -62,9 +62,6 @@ export async function selectStorageAccountTreeItemForCommand(
             if (enableResponse) {
```
Comment (StephenWeatherford) [inline src/azureStorageExplorer/selectStorageAccountNodeForCommand.ts]: after release, clean this up
