### PR TITLE
Set ext.attachedStorageAccountsTreeItem on activation

### LINKED ISSUE #1044: Fail to execute the command "Azure Storage: Attach Storage Account" with an error from command palette
**OS:** All
**Azure Resource Extension Build Version:** 20220505.12 (unified)
**Azure Storage Extension Build Version:** 20220505.2 (unified)
**Regression:** Not a regression

**Repro Steps:**

1. Make sure the "WORKSPACE" node is unexpanded -> Restart VS Code.
    Screen Shot 2022-05-07 at 14 10 38
2. F1 -> Azure Storage: Attach Storage Account.
3. Check whether succeeds to execute the command "Azure Storage: Attach Storage Account" or not.

**Expect:**
Succeed to execute the command "Azure Storage: Attach Storage Account".

**Actual:**
Fail to execute the command "Azure Storage: Attach Storage Account" with an error.
Screen Shot 2022-05-07 at 14 29 57

**More Info:**
This issue doesn't reproduce after expanding the "WORKSPACE" node.

### PR DESCRIPTION
**Pull request by alexweininger**
Fixes #1044

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -153,7 +153,11 @@ export async function activateInternal(context: vscode.ExtensionContext, perfSta
         const api = rgApiProvider.getApi<AzureHostExtensionApi>('0.0.1');
         ext.rgApi = api;
         api.registerApplicationResourceResolver('microsoft.storage/storageaccounts', new StorageAccountResolver());
-        ext.rgApi.registerWorkspaceResourceProvider('ms-azuretools.vscode-cosmosdb', new StorageWorkspaceProvider());
+
+        const workspaceRootTreeItem = (await ext.rgApi.workspaceResourceTree.getChildren())[0] as AzExtParentTreeItem;
+        const storageWorkspaceProvider = new StorageWorkspaceProvider(workspaceRootTreeItem);
+
+        ext.rgApi.registerWorkspaceResourceProvider('ms-azuretools.vscode-cosmosdb', storageWorkspaceProvider);
```
Comment (nturinski) [inline src/extension.ts:160]: I think you have to pull the changes from main.  It didn't take the provider id change.

**Review by nturinski — APPROVED** [review]

**Comment by nturinski** [comment]
image

**Comment by alexweininger** [comment]
> giphy

Took longer than I want to admit to understand 🤣

**Review by bwateratmsft — APPROVED** [review]
