### PR TITLE
Deploy static website: Show dist, out and build folders if they exist.

### LINKED ISSUE #173: Deploy action from sash can lead to the wrong folder being deployed
My current workspace is a webapp project. I wish to deploy a specific folder (say, the out folder)
I used the deploy button from the sash. Since the default option on the prompt is my workspace. Clicking on it would deploy the whole project, rather than list sub-folders. 
staticwebsitedeploy

### PR DESCRIPTION
**Pull request by PrashanthCorp**
Fixes #173, #176

### CODE REVIEW

**Comment by PrashanthCorp** [comment]
PIng.

File: src/azureStorageExplorer/blobContainers/quickPickUtils.ts [hunk 1]
```diff
@@ -3,53 +3,68 @@
...
+                }
+
+                folderQuickPickItems.push({
+                    label: path.basename(fsPath),
+                    description: fsPath,
+                    data: fsPath
+                });
+
+                // If the workspace has any of build, dist, or out, show those as well
+                const buildDefaultPaths = ["build", "dist", "out"];
```
Comment (StephenWeatherford) [inline src/azureStorageExplorer/blobContainers/quickPickUtils.ts]: Personally I'd put this at the top of the file, but I'll leave that up to you.

Comment (PrashanthCorp) [reply src/azureStorageExplorer/blobContainers/quickPickUtils.ts]: Not being used anywhere else (not being exported), so I'll leave it here at the moment.
