### PR TITLE
Make error message for duplicate tables/queues consistent

### LINKED ISSUE #482: [Suggestion] Keep the error message consistent when creating an existing queue and table
**OS:** All
**Build Version:** [20191008.20](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=11007)
**Regression:** Not a Regression

**Repro Steps:**

1. Navigate to one storage account in VS Code.
2. Create an existing queue and table.
3. Check the error messages.

**Actual:**
The error message is inconsistent. The error is clear for queue, need to check the detail error for table in output window.
image

**Suggestion:**
Keep the error message consistent.

### PR DESCRIPTION
**Pull request by wwlorey**
Fixes #482

### New error messages
Screen Shot 2019-10-28 at 2 35 26 PM

### Old error messages
Duplicate table: 
Screen Shot 2019-10-28 at 2 36 58 PM

No error message was originally displayed for a duplicate queue.

### CODE REVIEW

File: src/azureStorageExplorer/tables/tableGroupNode.ts [hunk 1]
```diff
@@ -78,13 +78,16 @@ export class TableGroupTreeItem extends AzureParentTreeItem<IStorageRoot> {
...
-    // tslint:disable-next-line:promise-function-async // Grandfathered in
-    private createTable(name: string): Promise<azureStorage.TableService.TableResult> {
+    private async createTable(name: string): Promise<azureStorage.TableService.TableResult> {
         return new Promise((resolve, reject) => {
             let tableService = this.root.createTableService();
-            tableService.createTable(name, (err?: Error, result?: azureStorage.TableService.TableResult) => {
+            tableService.createTable(name, (err?: Error | azureStorage.StorageError, result?: azureStorage.TableService.TableResult) => {
                 if (err) {
-                    reject(err);
+                    if ('code' in err && err.code === "TableAlreadyExists") {
```
Comment (EricJizbaMSFT) [inline src/azureStorageExplorer/tables/tableGroupNode.ts]: use `parseError(err).errorType`
