### PR TITLE
Fix multiple errors for invalid folders.url

### LINKED ISSUE #546: Display multiple errors when the folders.url is invalid for a blob container
**OS:** All
**Build Version:** [20191222.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13295&view=results)
**Regression:** Not a Regression

**Repro Steps:**
1. Enable "Azure Storage: Enable View In File Explorer".
2. Create a new storage account --> Create a blob container --> Open this blob container in File Explorer.
3. Save the workspace locally --> Set the folders.url as invalid like remove the blob container name.
4. Open the edited workspace in VS Code --> Pop up an error.
5. Check the Output window.

**Expect:**
Pop up one error.

**Actual:**
Display multiple errors.
image

**More Info:**
This issue doesn't reproduce for file share.

### PR DESCRIPTION
**Pull request by wwlorey**
For an invalid `folders.url` (created by removing the blob container name), `lookupRoot` is called many times for all the URIs present. Each time, an error would be thrown since the root `BlobContainerGroupTreeItem` didn't exist.

This fix displays only one `lookupRoot` error per `rootName`

Fixes #546

### CODE REVIEW

File: src/AzureStorageFS.ts [hunk 1]
```diff
@@ -385,7 +386,20 @@ export class AzureStorageFS implements vscode.FileSystemProvider {
...
-            throw new RangeError(`Unexpected entry ${treeItem.constructor.name}.`);
+            // Ensure only one RangeError is displayed per rootName
+            if (!context.errorHandling.suppressDisplay) {
+                let cache = this._rangeErrorCache.get(rootName);
+
+                // A RangeError has already been or will be thrown for this rootName
+                this._rangeErrorCache.set(rootName, true);
+
+                if (!cache) {
+                    throw new RangeError(`Unexpected entry ${treeItem.constructor.name}.`);
```
Comment (EricJizbaMSFT) [inline src/AzureStorageFS.ts]: A RangeError like this is usually only meant for internal use so we can catch it in telemetry. If users are seeing it (which seems possible based on the repro steps), I think that's a sign we should handle this better. For example:
- Can you try throwing a `FileSystemError` and see if that prevents "lookupRoot is called many times" (since VS Code theoretically handles those errors differently than normal errors)
- Let's improve the message. I'm thinking something as simple as "Invalid uri" would be better

Comment (wwlorey) [reply src/AzureStorageFS.ts]: There's still one error per URI with `FileSystemError`. Would it be better to use that or just `Error`?

Comment (wwlorey) [reply src/AzureStorageFS.ts]: And if we use an error message like "invalid uri", would be display the uri as well? If so we may want to see all the error messages since each one would be different

Comment (EricJizbaMSFT) [reply src/AzureStorageFS.ts]: What do you mean "per uri"? How many uris are there and what are they?

Comment (wwlorey) [reply src/AzureStorageFS.ts]: Each of the errors happened because it tried to read some file as a `BlobContainerGroupTreeItem` or the equivalent for fie shares. I modified the original error message to show those files:

Screen Shot 2020-01-14 at 1 55 18 PM

I'm not sure where they are coming from. Maybe they're from where VS Code opened the workspace?

Comment (EricJizbaMSFT) [reply src/AzureStorageFS.ts]: Oh did you use `getFileSystemError` or FileSystemError directly? Check a few lines up for an example of `getFileSystemError`

Comment (EricJizbaMSFT) [reply src/AzureStorageFS.ts]: It makes sense that VS Code is looking for those files on startup. It needs to know it's own settings, git config, etc. because that directly affects some of VS Code's behavior. I believe the proper fix in this case is to throw a FileNotFound using `getFileSystemError` in effect telling VS Code "We ain't got no settings for you"

Comment (wwlorey) [reply src/AzureStorageFS.ts]: Using `getFileSystemError` does the trick 👌
