### PR TITLE
Fixes error messages when opening blob in explorer

### LINKED ISSUE #1132: An error occurs after opening a blob container in the explorer
**OS:** Win10
**Build Version:** 20220825.16
**Regression:** Previous release

**Repro Steps:**
1. Create a storage account -> Create a new blob container -> Right click the blob container -> Click "Open in Explorer..." -> Click "Open in current window".
2. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
image
Details in Output:
```
Error: The specified blob does not exist.
RequestId:07b6f3d2-501e-0088-5521-b98baf000000
Time:2022-08-26T07:55:23.0806835Z
Error: The specified blob does not exist.
RequestId:9bffb297-c01e-0033-4321-b9310d000000
Time:2022-08-26T07:55:23.0876143Z
Error: The specified blob does not exist.
RequestId:11e8cd22-501e-0098-7521-b94ec7000000
Time:2022-08-26T07:55:23.0978636Z
Error: The specified blob does not exist.
RequestId:c4c11f09-401e-003d-7a21-b918bd000000
Time:2022-08-26T07:55:23.1031379Z
Error: The specified blob does not exist.
RequestId:34654c60-301e-00a1-5e21-b9b5db000000
Time:2022-08-26T07:55:23.1265809Z
Error: The specified blob does not exist.
RequestId:92d1433f-201e-0004-6821-b9e3a1000000
Time:2022-08-26T07:55:23.1106343Z
Error: The specified blob does not exist.
RequestId:b4f0b0b4-501e-006c-4321-b98531000000
Time:2022-08-26T07:55:23.1189146Z
Error: The specified blob does not exist.
RequestId:3ffeeae5-401e-0012-4d21-b91576000000
Time:2022-08-26T07:55:23.1260806Z
Error: The specified blob does not exist.
RequestId:9abb241b-401e-004f-2721-b91ff2000000
Time:2022-08-26T07:55:23.1360358Z
Error: The specified blob does not exist.
RequestId:00db5663-701e-006b-1c21-b9e952000000
Time:2022-08-26T07:55:23.8214322Z
Error: The specified blob does not exist.
RequestId:ade232cc-601e-0058-7421-b9b6f9000000
Time:2022-08-26T07:55:24.2223143Z
Error: The specified blob does not exist.
RequestId:a34741a4-f01e-0091-1021-b90b14000000
Time:2022-08-26T07:55:24.5826062Z
```

### PR DESCRIPTION
**Pull request by motm32**
Fixes #1132. Not sure if this is how we would want to do it but this is the only thing I found that could get rid of those error messages. Also takes takes care of the error message seen in #1136.

### CODE REVIEW

File: src/AzureStorageFS.ts [hunk 1]
```diff
@@ -215,7 +215,7 @@ export class AzureStorageFS implements vscode.FileSystemProvider, vscode.TextDoc
     async readFile(uri: vscode.Uri): Promise<Uint8Array> {
         let client: ShareFileClient | BlobClient;
         let downloaded: FileDownloadResponseModel | BlobDownloadResponseModel;
-        return await callWithTelemetryAndErrorHandling('readFile', async (context) => {
+        return await callWithTelemetryAndErrorHandlingSync('readFile', async (context) => {
```
Comment (bwateratmsft) [inline src/AzureStorageFS.ts:218]: I don't think this is the fix we're looking for. The `callWithTelemetryAndErrorHandlingSync` method is for use in non-async methods. This one is already async, so there should be almost no difference between `await callWithTelemetryAndErrorHandling` and `callWithTelemetryAndErrorHandlingSync`.

**Review by bwateratmsft — CHANGES_REQUESTED** [review]

File: src/AzureStorageFS.ts (hunk 1 above)
Comment (motm32) [reply src/AzureStorageFS.ts:218]: Sounds good! I expected it was not what we wanted to do, but thought it was weird that it got rid of the error messages even though both should have similar behaviors.

File: src/AzureStorageFS.ts [hunk 2]
```diff
@@ -216,6 +216,8 @@ export class AzureStorageFS implements vscode.FileSystemProvider, vscode.TextDoc
         let client: ShareFileClient | BlobClient;
         let downloaded: FileDownloadResponseModel | BlobDownloadResponseModel;
         return await callWithTelemetryAndErrorHandling('readFile', async (context) => {
+            context.errorHandling.rethrow = true;
+            context.errorHandling.suppressDisplay = true;
```
Comment (alexweininger) [inline src/AzureStorageFS.ts:220]: We weren't sure why these were removed in https://github.com/microsoft/vscode-azurestorage/pull/1102 (accidental perhaps), so we'll add them back for now.

My only worry is that rethrow = false (default) could have been a fix for the issues in #1102.

**Review by bwateratmsft — APPROVED** [review]

**Review by alexweininger — APPROVED** [review]
